### ISSUE TITLE
Disambiguation of square shaped symbols

### ISSUE THREAD

**Issue by laurentalacoque** [romlemaire/MiamProtocol#2]
Hi @romlemaire, thanks for this great work!
I feel that the square shaped events can be ambiguous, so I submited PR #1 
Please feel free to comment and review it.

**Comment by romlemaire** [comment]
Good afternoon @laurentalacoque!
Your proposition makes a lot of sense. I've already merged it to the master branch.

**Comment by laurentalacoque** [comment]
Thanks!
