### ISSUE TITLE
Make timing parameters optional

### ISSUE THREAD

**Issue by laurentalacoque** [romlemaire/MiamProtocol#3]
Some event-types currently require a timestamping parameter although the transmission mean [WhatsApp](https://www.whatsapp.com/) already provides this.

Shouldn't these parameter be marked as optional ?

### Affected action types
| Syntaxe           | Explications  |
|:------------------- |:------------- |
| 🔹 [Hx] *hh:mm* / N | Départ effectif, heure et nombre de personnes. Destination optionnelle, H1 la plupart du temps. |
| ◾️ *hh:mm*          | Confirmation d’arrivée à destination. |

**Comment by romlemaire** [comment]
I agree we could make these parameter optional the same way the destination is.
Would you mind preparing a pull request intended to solve this issue?

**Comment by laurentalacoque** [comment]
I just submited PR #4 that introduces the principle of parcimony.
I feel that it would be better to accept the Manifesto first, so that every issue could be evaluated wrt. it

**Comment by laurentalacoque** [comment]
Solved by #4
